# This was created by modifing github's 'CMake on multiple platforms'
name: VFE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # reference: https://github.com/danielzsh/spark/blob/master/.github/workflows/compile.yml
  windows-build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "examples-dir=${{ github.workspace }}/build/examples" >> "$GITHUB_OUTPUT"

    - name: Build (Windows)
      run: |
        mkdir ${{ steps.strings.outputs.build-output-dir }}

        cl ${{ github.workspace }}/compiler.c /Fe:${{ steps.strings.outputs.build-output-dir }}/fictiler
        cl ${{ github.workspace }}/decompiler.c /Fe:${{ steps.strings.outputs.build-output-dir }}/devirtual
        cl ${{ github.workspace }}/virtual_emulator.c /Fe:${{ steps.strings.outputs.build-output-dir }}/vimulator
    

    - name: Test (Windows)
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: cmd
      run: |
        mkdir examples

        setlocal EnableDelayedExpansion
        for %%f in (..\examples\*) do (

          set file=%%f

          for %%i in ("!file!") do(
            set filename_without_extension=%%~ni
            set "extension=%%~xi"
          )

          if /i "!extension!"==".fiction" (
            .\fictiler %%f  examples/!filename_without_extension!.virtual
          )

        )
        endlocal



  linux-macos-build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "examples-dir=${{ github.workspace }}/build/examples" >> "$GITHUB_OUTPUT"

    - name: Build (Linux and MacOS)
      run: |
        mkdir ${{ steps.strings.outputs.build-output-dir }}
        ${{ matrix.c_compiler }} ${{ github.workspace }}/compiler.c -o ${{ steps.strings.outputs.build-output-dir }}/fictiler
        ${{ matrix.c_compiler }} ${{ github.workspace }}/decompiler.c  -o ${{ steps.strings.outputs.build-output-dir }}/devirtual
        ${{ matrix.c_compiler }} ${{ github.workspace }}/virtual_emulator.c -o ${{ steps.strings.outputs.build-output-dir }}/vimulator
      
    - name: Test (Linux and MacOS)
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        mkdir -p examples

        for file in ../examples/*; do
        
          filename="${file%.*}"
          extension="${file##*.}"

          if [[ "$extension" == "fiction" ]]; then
            ./fictiler "../examples/$file" "examples/$(basename "$filename").virtual"
          fi

        done

